---
- name: 'GET DATA FROM DEVICE'
  hosts: 'ceos'
  connection: 'network_cli'
  gather_facts: false
  tasks:
    - name: 'VALIDATE DEVICES ARE REACHABLE'
      ansible.builtin.ping:
      register: 'ping'

    - name: 'VIEW OUTPUT OF PING'
      ansible.builtin.debug:
        var: 'ping'

    - name: 'ANNOY PAUL'
      ansible.builtin.debug:
        msg: "I like you"

    - name: 'SHOW VERSION'
      ansible.utils.cli_parse:
        command: 'show version'
        parser:
          name: 'ansible.netcommon.ntc_templates'
      register: 'version_result'

    - name: '{{ inventory_hostname | upper }} OS VERSION'
      ansible.builtin.debug:
        msg: "{{ version_result['parsed'][0]['image'] }}"
