---
hostname: clab-lab-01-ceos1
ansible_network_os: "arista.eos.eos"
domain_name: ceos1.local
router_id: 172.200.210.11
interfaces:
  - eos_if: "Ethernet1/1"
    desc: "Ethernet1/1 - Srl to ceos1 peering intf"
    enabled: true
    routed: true
    ipv4: 192.168.1.1/31
  - eos_if: "Loopback0"
    desc: "Loopback0 - Update Source"
    enabled: true
    ipv4: 172.200.210.11/32
bgp:
  local_as: 65001
  neighbors:
    ipv4_neighbors:
     - neighbor: 192.168.1.0
       remote_as: 65100
       update_source: Loopback0
       prefix: '172.200.210.11'
       masklen: 32
