---
hostname: clab-lab-01-ceos2
ansible_network_os: "arista.eos.eos"
domain_name: ceos2.local
router_id: 172.200.210.13
interfaces:
  - eos_if: "Ethernet1/1"
    desc: "Ethernet1/1 - Srl to ceos2 peering intf"
    enabled: true
    routed: true
    ipv4: 192.168.1.3/31
  - eos_if: "Loopback0"
    desc: "Loopback0 - Update Source"
    enabled: true
    ipv4: 172.200.210.13/32
bgp:
  local_as: 65002
  neighbors:
    ipv4_neighbors:
     - neighbor: 192.168.1.2
       remote_as: 65100
       update_source: Loopback0
       prefix: '172.200.210.13'
       masklen: 32