---
hostname: clab-lab-01-ceos2
ansible_network_os: "arista.eos.eos"
domain_name: ceos2.local
interfaces:
  - eos_if: "Ethernet1/1"
    desc: "Ethernet1/1 - Srl to ceos2 peering intf"
    enabled: true
    routed: true
    ipv4: 192.168.1.3/31
  - eos_if: "Loopback0"
    desc: "Loopback0 - Update Source"
    enabled: true
    ipv4: 10.10.10.11/32
bgp:
  router_id: 172.200.210.13
  local_as: 65002
  neighbors:
    ipv4_neighbors:
      - peer: 192.168.1.2
        remote_as: 65100
        networks:
          - 10.10.10.10/32
          - 11.1.1.0/24
          - 4.4.4.0/24
